<?php

/**
 * Previous Next Navigation Extension for Magento 2
 *
 * @author     Volodymyr Konstanchuk http://konstanchuk.com
 * @copyright  Copyright (c) 2017 The authors
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/** @var $block \Konstanchuk\PrevNextNavigation\Block\PreviousUrl */

?>
<script type="text/x-magento-init">
    {
        "*": {
            "konstanchuk/prevNextNavigationPreviousUrl": {
                "current_category_id": <?php echo json_encode($block->getCurrentCategory()->getId()); ?>
            }
        }
    }
</script>